
Console . Write( " texto a ser traduzido : " );
Console . WriteLine (
Console . ReadLine ()    

.Replace ( "a" , "KA" )
.Replace ( "b" , "ZU" )
.Replace ( "c" , "MI" )
.Replace ( "d" , "TE" )
.Replace ( "e" , "KU" )
.Replace ( "f" , "LU" )
.Replace ( "g" , "JI" )
.Replace ( "h" , "RI" )
.Replace ( "i" , "KI" )
.Replace ( "j" , "ZUS" )
.Replace ( "k" , "ME" )
.Replace ( "l" , "TA" )
.Replace ( "m" , "RIN" )
.Replace ( "n" , "PARA" )
.Replace ( "o" , "MO" )
.Replace ( "p" , "NÃO" )
.Replace ( "q" , "KE")
.Replace ( "r" , "SHI" )
.Replace ( "s" , "ARI" )
.Replace ( "t" , "CHI" )
.Replace ( "u" , "DO" )
.Replace ( "v" , "RV" )
.Replace ( "w" , "MEI" )
.Replace ( "x" , "NA" )
.Replace ( "y" , "FV" )
.Replace ( "z" , "ZI" )
);